### ISSUE TITLE
Cannot make 'sql' component of database collections due to UTC_Time_Offset not visible.

### ISSUE THREAD

**Issue by srb623** [AdaCore/gnatcoll-db#16]
I have compiled these components in the past, but today when I tried (have not done it for a while - so did a fetch from git), it fails when I try to build the 'sql' component, which then as this is needed for some of the other components, causes them to fail as well.  I have performed a 'make -C sql clean' and then a 'make -C sql setup' before the 'make -C sql'.  The make command produces the following error message:

```sh
gprbuild -p -m --target=x86_64-linux  -j2 -XGNATCOLL_VERSION=0.0 -XBUILD=PROD  -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
	gnatcoll_sql.gpr
Compile
   [Ada]          gnatcoll-sql_impl.adb
   [Ada]          gnatcoll-sql-sessions.adb
gnatcoll-sql_impl.adb:1679:44: "UTC_Time_Offset" is not visible (more references follow)
gnatcoll-sql_impl.adb:1679:44: non-visible declaration at a-catizo.ads:28
gnatcoll-sql_impl.adb:1679:44: non-visible declaration at a-calend.ads:403

   compilation of gnatcoll-sql_impl.adb failed

gprbuild: *** compilation phase failed
make: *** [Makefile:116: build-static] Error 4
```

I am using GNAT 2020 but have also built the git version of gprbuild.  Using this produces the same failure.  I am presuming that my setup is at fault and would appreciate any help that people are willing to provide.

**Comment by anisimkov** [comment]
You should build and install gnatcoll-core before gnatcoll-db
