### ISSUE TITLE
gnatinspect.gpr missing.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gnatcoll-db#2]
Hello,
gnatinspect.gpr file is missing in gnatinspect folder.
HTH, Pascal.

**Comment by steve-cs** [comment]
@Blady-Com, if this is blocking you might want to try the patch that I'm using to build it.

https://github.com/steve-cs/gnat-builder/blob/master/patches/gnatcoll-db-src-patch-1

**Comment by t-14** [comment]
Sorry about that, we'll fix it. @steve-cs's project looks ok as a workaround at a glance.
