### ISSUE TITLE
gnatinspect database has some case sensitive columns

### ISSUE THREAD

**Issue by Labdabeta** [AdaCore/gnatcoll-db#8]
Some columns seemingly at random in the sql database generated by gnatinspect are case sensitive when by default they would not be. In particular `name`, `language`, `path`, `fromEntity`, `toEntity`, `fromFile`, `toFile`, and `column` are case sensitive in the database. 

This makes analysing the database manually more difficult and should be an easy fix. 

I don't know where xref/generated/gnatcoll-xref-database_names.ads is generated from, but it is clearly visible there that some names are surrounded in extra quotes `NC_Path : aliased constant String := """path""";` while most are not `NC_Stamp : aliased constant String := "stamp";`.

**Comment by Labdabeta** [comment]
Side-note/possible feature request: For my purposes when I use the generated gnatinspect database in a command-line utility I wrote I have to manually add id primary key autoincrements to some of the tables that lack them in order to more easily manipulate them. Proper SQL style would have those in any relevant table (i.e. f2f, e2e, and entity_refs).

**Comment by briot** [comment]
> Some columns seemingly at random in the sql database generated by gnatinspect are case sensitive when by default they would not be. In particular name, language, path, fromEntity, toEntity, fromFile, toFile, and column are case sensitive in the database.
> This makes analysing the database manually more difficult and should be an easy fix.

I don’t think it will be an easy fix for AdaCore. If you think of it, it will impact all existing tools that
directly access the database, as yours do apparently. So changing the name of the columns is
a significant change, and probably not worth it.

I agree it is unfortunate that extra quoting is needed for some column names, but fortunately when
you access the database from Ada, this is all taken care of for you by GNATCOLL.

Note that these extra quotes are only needed with postgresql. sqlite for instance is completely happy
with not having extra quotes:

     > select * from f2f where fromFile=7;
     4|1|1
     4|5|0

gnatinspect was primarily developed with short-lived databases in mind (or at least databases that can be
wiped out easily and then recreated), and thus preferably with sqlite.

> I don't know where xref/generated/gnatcoll-xref-database_names.ads is generated from, but it is clearly visible there that some names are surrounded in extra quotes NC_Path : aliased constant String := """path"""; while most are not NC_Stamp : aliased constant String := "stamp";.

That file is generated by gnatcoll_db2ada, from src/dbschema.txt.
The latter contains a lot of comments, if you are interested in the design of the database.

> Side-note/possible feature request: For my purposes when I use the generated gnatinspect database in a command-line utility I wrote I have to manually add id primary key autoincrements to some of the tables that lack them in order to more easily manipulate them. Proper SQL style would have those in any relevant table (i.e. f2f, e2e, and entity_refs).

Only entity_refs doesn’t have a primary key.
e2e has (fromEntity, toEntity, kind) as a primary key, and f2f uses (fromFile, toFile, kind)
There is no logical primary key for entity_refs, so making one up with an autoincrement field
is bringing no information compared to using the default of the database (the row id). Best SQL
practices certainly do not encourage creating dummy data in such cases.

Emmanuel
former developer of gnatinspect
No longer with AdaCore, so not speaking on their behalf
